package defencesystem;

public class Submarine extends javax.swing.JFrame {

    public Submarine() {
        initComponents();
        setTitle("Submarine");
        setResizable(false);
        setLocationRelativeTo(null);
        
        shootBtn.setEnabled(false);
        tomahawkBtn.setEnabled(false);
        tridentBtn.setEnabled(false);
        sonarBtn.setEnabled(false);
        
    }
    
    
    public void setAreaStatus(int result){
        if(result == 0){
            areaStatusLbl.setText("Area Not Cleared");
        }else if(result ==1){
            areaStatusLbl.setText("Area Cleared");
        }
    }
    
    public void buttonOperationSubamarine(int sliderValue){
        if(sliderValue >= 25){
            shootBtn.setEnabled(true);
        }
        if(sliderValue >= 50){
            sonarBtn.setEnabled(true);
        }
        if(sliderValue >=75){
            tomahawkBtn.setEnabled(true);
        }
        if(sliderValue >=100){
            tridentBtn.setEnabled(true);
        }
        if(sliderValue < 100){
            tridentBtn.setEnabled(false);
        }
        if(sliderValue < 75){
            tomahawkBtn.setEnabled(false);
        }
        if(sliderValue < 50){
            sonarBtn.setEnabled(false);
        }
        if(sliderValue < 25){
            shootBtn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        areaStatusLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTxtArea = new javax.swing.JTextArea();
        msgTxtField = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        shootBtn = new javax.swing.JButton();
        sonarBtn = new javax.swing.JButton();
        tomahawkBtn = new javax.swing.JButton();
        tridentBtn = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        areaStatusLbl.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        areaStatusLbl.setForeground(new java.awt.Color(0, 102, 153));
        areaStatusLbl.setText("Area Not Cleared");

        contentTxtArea.setBackground(new java.awt.Color(0, 204, 204));
        contentTxtArea.setColumns(20);
        contentTxtArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contentTxtArea.setRows(5);
        jScrollPane1.setViewportView(contentTxtArea);

        msgTxtField.setBackground(new java.awt.Color(0, 204, 204));
        msgTxtField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        sendBtn.setBackground(new java.awt.Color(0, 102, 102));
        sendBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sendBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendBtn.setText("SEND");

        shootBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        shootBtn.setForeground(new java.awt.Color(0, 102, 102));
        shootBtn.setText("Shoot");

        sonarBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sonarBtn.setForeground(new java.awt.Color(0, 102, 102));
        sonarBtn.setText("Sonar Operation");

        tomahawkBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tomahawkBtn.setForeground(new java.awt.Color(0, 102, 102));
        tomahawkBtn.setText("Tomahawk Missile");

        tridentBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tridentBtn.setForeground(new java.awt.Color(0, 102, 102));
        tridentBtn.setText("Trident - 2 Missile");

        jCheckBox1.setBackground(new java.awt.Color(204, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 51, 102));
        jCheckBox1.setText("Position");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(msgTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sendBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(areaStatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(shootBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tomahawkBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sonarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tridentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(areaStatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sonarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(shootBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tomahawkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tridentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            DeffenceObserver.setPositionSubmarine(true);
        }else{
            DeffenceObserver.setPositionSubmarine(false);
            shootBtn.setEnabled(false);
            tridentBtn.setEnabled(false);
            tomahawkBtn.setEnabled(false);
            sonarBtn.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaStatusLbl;
    private javax.swing.JTextArea contentTxtArea;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField msgTxtField;
    private javax.swing.JButton sendBtn;
    private javax.swing.JButton shootBtn;
    private javax.swing.JButton sonarBtn;
    private javax.swing.JButton tomahawkBtn;
    private javax.swing.JButton tridentBtn;
    // End of variables declaration//GEN-END:variables
}
